// AirplaneState.hpp
#ifndef AIRPLANE_STATE_HPP // include guard
#define AIRPLANE_STATE_HPP

enum AirplaneState
{
    AIRPLANE_STOPPED = 0,
    AIRPLANE_ASKING_PERMISSION_TO_TAKE_OFF,
    AIRPLANE_TAKING_OFF,
    AIRPLANE_FLYING,
    AIRPLANE_ASKING_PERMISSION_TO_LAND,
    AIRPLANE_LANDING,
    AIRPLANE_CRASHED
};

#endif /* AIRPLANE_STATE_HPP */